baseURL: https://29x10.github.io
languageCode: en-us
title: coding camp
theme: PaperMod

menu:
  main:
    - name: Archive
      url: archives/
    - name: Tags
      url: tags/
    - name: Categories
      url: categories/

params:
  ShowToc: true
  TocOpen: true
  displayFullLangName: true
  ShowCodeCopyButtons: true
  ShowReadingTime: true
  homeInfoParams:
    Title: "Coding Camp"
    Content: >
      Welcome to Jerome's coding camp.
      
      - Hopefully there are take away when you leave.

  